[package]
name = "game_engine"
version = "0.1.0"
edition = "2021"
include = ["/src"]

[dependencies]

[build-dependencies]
bindgen = "0.65.1"
cc = "1.1.37"

[[test]]
name = "test_simple_game_loop"
path = "tests/test_simple_game_loop.rs"
harness = false