[package]
name = "rust_test_game"
version = "0.1.0"
edition = "2021"

[dependencies]
game_engine = { path = "../game_engine" }
reqwest = { version = "0.12.9", features = ["json", "blocking"] }
serde = { version = "1.0.215", features = ["derive"] }
